import React, { useState, useMemo, useRef } from "react";
import {
  safeGetComputedStyle,
  getGraphColors,
  getChartColors,
} from "./themeColors";
export const pointRadius = 4;
export const pointHoverRadius = 6;
export const pointBorderWidth = 2;
export const tension = 0;
export const borderDash = [12, 8];
export const currentColors = getGraphColors();
export const currentSurfaceColor = getChartColors()[2];
export const textColor = getChartColors()[1];
export const labelColor = safeGetComputedStyle("--color-text-default", "#000000");
export const gridColor = safeGetComputedStyle("--color-border-primary", "#e0e0e0");
export const fontFamily = safeGetComputedStyle("--font-family-graphs", "sans-serif");
/**Labels Graph - START */
export const labelsMonths = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
export const labelsQuarter = ["Q1", "Q2", "Q3", "Q4"];
export const labelsSemester = ["S1", "S2"];
/** Labels Graph - END */
/**Legend Graph - START */
export const legendDataSetUp = {
  display: false,
  position: "bottom",
  labels: {
    color: labelColor,
    usePointStyle: true,
    pointStyle: "line",
    font: {
      family: fontFamily,
      size: 14,
    },
  },
};
/**Legend Graph - END */
/**tooltip Graph - START */
export const tooltipSetUp = {
  titleColor: labelColor,
  bodyColor: labelColor,
  backgroundColor: currentSurfaceColor,
  borderColor: safeGetComputedStyle("--color-text-default", "transparent"),
  borderWidth: 1,
};
/**tooltip Graph - END */
/**Scales Graph - START */
export const scalesSetUp = {
  x: {
    offset: true,
    ticks: {
      color: labelColor,
      font: {
        family: fontFamily,
        size: 12,
      },
    },
    grid: {
      color: gridColor,
      borderColor: gridColor,
    },
  },
  y: {
    beginAtZero: true,
    ticks: {
      color: labelColor,
      font: {
        family: fontFamily,
        size: 12,
      },
      callback: (value) => `$${(value / 1000).toFixed(0)}K`,
    },
    grid: {
      color: gridColor,
      borderColor: gridColor,
    },
  },
};
/**Scales Graph - END */
/**Overview Graph - START */
export const datasetsOverview = [
  {
    label: "OWNED CURRENT YEAR",
    data: [
      180000, 180000, 25000, 290000, 320000, 300000, 310000, 295000, 310000,
      320000, 350000, 120000,
    ],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [
      300000, 18000, 270000, 420000, 390000, 370000, 190000, 200000, 180000,
      230000, 270000, 250000,
    ],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [
      400000, 180000, 370000, 390000, 450000, 430000, 410000, 430000, 410000,
      400000, 390000, 300000,
    ],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [
      250000, 180000, 260000, 310000, 330000, 290000, 300000, 270000, 260000,
      310000, 320000, 310000,
    ],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
];
export const datasetsOverviewQuarter = [
  {
    label: "OWNED CURRENT YEAR",
    data: [180000, 180000, 25000, 290000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [300000, 18000, 270000, 420000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [400000, 180000, 370000, 390000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [250000, 180000, 260000, 310000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
];
export const datasetsOverviewSemester = [
  {
    label: "OWNED CURRENT YEAR",
    data: [180000, 180000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [300000, 18000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [400000, 180000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [250000, 180000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
];
export const legendDataOverview = [
  {
    label: "OWNED",
    style: "cube",
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "PROSPECTS",
    style: "cube",
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "PREVIOUS YEAR",
    style: "line",
    borderColor: textColor,
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "CURRENT YEAR",
    style: "line",
    borderColor: textColor,
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
  },
];

/**Overview Graph - END */
/**Prospects Graph - START */
export const datasetsProspects = [
  {
    label: "OWNED CURRENT YEAR",
    data: [
      180000, 180000, 250000, 290000, 320000, 300000, 310000, 295000, 310000,
      320000, 350000, 120000,
    ],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [
      300000, 180000, 270000, 420000, 390000, 370000, 190000, 200000, 180000,
      230000, 270000, 250000,
    ],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS CURRENT YEAR",
    data: [
      200000, 180000, 230000, 250000, 240000, 230000, 190000, 180000, 170000,
      190000, 200000, 180000,
    ],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius: pointRadius,
    pointHoverRadius: pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth: pointBorderWidth,
    tension: tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [
      400000, 18000, 370000, 390000, 450000, 430000, 410000, 430000, 410000,
      400000, 390000, 300000,
    ],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [
      250000, 180000, 260000, 310000, 330000, 290000, 300000, 270000, 260000,
      310000, 320000, 310000,
    ],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS PREVIOUS YEAR",
    data: [
      180000, 200000, 230000, 190000, 250000, 190000, 180000, 170000, 200000,
      240000, 180000, 230000,
    ],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth,
    tension,
  },
];
export const datasetsProspectsQuarter = [
  {
    label: "OWNED CURRENT YEAR",
    data: [180000, 180000, 250000, 290000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [300000, 180000, 270000, 420000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS CURRENT YEAR",
    data: [200000, 180000, 230000, 250000],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius: pointRadius,
    pointHoverRadius: pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth: pointBorderWidth,
    tension: tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [400000, 18000, 370000, 390000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [250000, 180000, 260000, 310000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS PREVIOUS YEAR",
    data: [180000, 200000, 230000, 190000],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth,
    tension,
  },
];
export const datasetsProspectsSemester = [
  {
    label: "OWNED CURRENT YEAR",
    data: [180000, 180000],
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT Previous YEAR",
    data: [300000, 180000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS CURRENT YEAR",
    data: [200000, 180000],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    fill: false,
    pointRadius: pointRadius,
    pointHoverRadius: pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth: pointBorderWidth,
    tension: tension,
  },
  {
    label: "OWNED PREVIOUS YEAR",
    data: [400000, 18000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "circle",
    tension,
  },
  {
    label: "PROSPECT CURRENT YEAR",
    data: [250000, 180000],
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointBorderWidth,
    pointStyle: "rectRounded",
    tension,
  },
  {
    label: "POTENTIAL PROSPECTS PREVIOUS YEAR",
    data: [180000, 200000],
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    borderDash,
    fill: false,
    pointRadius,
    pointHoverRadius,
    pointStyle: "crossRot",
    pointBorderWidth,
    tension,
  },
];
export const legendDataProspects = [
  {
    label: "OWNED",
    style: "cube",
    borderColor: currentColors[0],
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "PROSPECTS",
    style: "cube",
    borderColor: currentColors[1],
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "POTENTIAL PROSPECTS",
    style: "cube",
    borderColor: currentColors[2],
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "PREVIOUS YEAR",
    style: "line",
    borderColor: textColor,
    backgroundColor: currentSurfaceColor,
    fill: false,
  },
  {
    label: "CURRENT YEAR",
    style: "line",
    borderColor: textColor,
    backgroundColor: currentSurfaceColor,
    borderDash,
    // fill: false,
  },
];
/**Prospects Graph - END */
