export const mockAdvertisers = [
  {
    CreativeId: 1,
    viewport: "desktop",
    CreativePosition: "1",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-001.png",
    CreativeName: "ANIVERSÁRIO MART MINAS",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "80K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 2,
    viewport: "desktop",
    CreativePosition: "2",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-002.png",
    CreativeName: "Continue em movimento, Do Exercicio as crompas no BH!",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "18K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 3,
    viewport: "desktop",
    CreativePosition: "3",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-003.png",
    CreativeName: "Cheio de prêmios para você",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "23K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 4,
    viewport: "desktop",
    CreativePosition: "4",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-004.png",
    CreativeName: "ANIVERSÁRIO BH 24 ANOS",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "45K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 5,
    viewport: "desktop",
    CreativePosition: "5",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-005.png",
    CreativeName: "Ceias de Réveillon Verdemar",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "12K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 6,
    viewport: "desktop",
    CreativePosition: "6",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-006.png",
    CreativeName: "Preço baixo é no Mart Minas",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "78K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 7,
    viewport: "desktop",
    CreativePosition: "7",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-007.png",
    CreativeName: "DOCE DE LEITE VERDEMAR",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "4K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 8,
    viewport: "desktop",
    CreativePosition: "8",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-008.png",
    CreativeName: "12 de Dezembro",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "7K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 9,
    viewport: "desktop",
    CreativePosition: "9",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-009.png",
    CreativeName: "nas Lojas de Minas Gerais",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "6K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
  {
    CreativeId: 10,
    viewport: "desktop",
    CreativePosition: "10",
    creativeImagePath:
      "https://www.mariaalejandratellez.com/wp-content/uploads/2025/07/creative-image-portfolio-010.png",
    CreativeName: "QUINTA FERIA EPA",
    CreativeCurrencyValue: "$",
    CreativeCurrencyAmount: "2K",
    CreativeParent: "COMERCIO",
    CreativeCategory: "SUPER HIPERMERCADO ATACADISTA",
    CreativeAdvertiser: "MART MINAS",
    CreativeBrand: "MART MINAS",
    CreativeProduct: "MART MINAS",
    CreativeMedia: "Internet - Display",
    CreativeFirstOccurrence: "2025-07-01",
  },
];
